In [1]:
a = 1

In [2]:
type(a)

int

In [3]:
b=3,6

In [4]:
type(b)

tuple

In [5]:
c = 3.6

In [6]:
type(c)

float

In [7]:
cadena ='''hola
a todos
en varias lineas'''

In [8]:
cadena.lower()

'hola\na todos\nen varias lineas'

In [9]:
cadena = cadena.upper()

In [10]:
cadena

'HOLA\nA TODOS\nEN VARIAS LINEAS'

In [13]:
cadena[:4]

'HOLA'

In [14]:
lista = [1,2,3]

In [15]:
lista.append(5)

In [16]:
lista

[1, 2, 3, 5]

In [17]:
len(cadena)

29

In [18]:
len(lista)

4

In [21]:
matriz = [[1,2],[3,4]]

In [23]:
matriz[0][1]

2

In [24]:
lista*2

[1, 2, 3, 5, 1, 2, 3, 5]

In [25]:
matriz*2

[[1, 2], [3, 4], [1, 2], [3, 4]]

In [26]:
[v*2 for v in lista]

[2, 4, 6, 10]

In [27]:
import numpy as np

In [28]:
n = np.array([1,2,3])

In [30]:
n.shape

(3,)

In [32]:
n

array([1, 2, 3])

In [34]:
n[-1]

3

In [35]:
n*2

array([2, 4, 6])

In [41]:
n.dtype

dtype('int64')

In [42]:
np.int8

numpy.int8

In [43]:
np.uint8

numpy.uint8

In [45]:
z = np.zeros([2,2])

In [46]:
z

array([[0., 0.],
       [0., 0.]])

In [48]:
z.dtype

dtype('float64')

In [49]:
o = np.ones([2,3])

In [50]:
o

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
o[1,-1] = 7

In [52]:
o

array([[1., 1., 1.],
       [1., 1., 7.]])

In [53]:
o[:,0]

array([1., 1.])

In [54]:
o[1,:]

array([1., 1., 7.])

In [55]:
o[:,0] + 3

array([4., 4.])

In [56]:
o

array([[1., 1., 1.],
       [1., 1., 7.]])

In [57]:
o[:,0] += 3

In [58]:
o

array([[4., 1., 1.],
       [4., 1., 7.]])

In [59]:
o.T

array([[4., 4.],
       [1., 1.],
       [1., 7.]])

In [60]:
np.linalg(o @ o.T)

TypeError: 'module' object is not callable